"""Add OAuth fields to User model

Revision ID: 25293091846e
Revises: 42bc3ec96739
Create Date: 2024-10-05 19:23:41.458374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25293091846e'
down_revision: Union[str, None] = '42bc3ec96739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oauth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_token')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
